#19356 Snowflake転送先時の転送ジョブエラー時に一時STAGEが残ってしまう問題の解消
trocco-io/embulk-output-snowflake pull request #72
Opened 2024-02-26 06:01 UTC by maeken

# この PR はなぜ必要なのか
- Snowflake転送先時の転送ジョブエラー時に一時STAGEが残ってしまう問題への対応の修正

# この PR は何をやっているのか

- 以下の方針に従って一時STAGEのcreate, drop処理を修正
  - 方針
    - runDropStageはrunCreateStageと同じレベルで行うようにする
    - そもそもrunCreateStageの実行箇所が分割されたジョブのマルチスレッド起動部だったので、CREATE STAGE IF EXIST句はスレッド数分実行されていた。IF EXISTSなので動作としては問題なかったが、DROPは先行スレッドが削除してしまうと後続スレッドでエラーになる。ジョブの処理全体を包括できるOutputPluginのtransaction処理内でcreate、dropを完結させる。
    - 既存の不要なcreate、drop処理は削除

# Issue / Reference

- ref: https://github.com/primenumber-dev/n-transfer-ui/issues/19356

## レビューポイント

- 修正実装方針の検証

## スクリーンショット

# リリース前後作業

- [ ] 特になし

# staging 確認

## 動作検証担当者

- [ ] QA 担当による staging 確認を希望するため、検証内容を記載しました。
- [ ] 自ら staging 確認を実施します。検証内容を記載しました。
- [ ] staging 確認は不要です。

## 検証内容

- [ ] 転送先Snowflakeのジョブで、大小ある転送データの転送が正常完了すること。
- [ ] 転送先Snowflakeのジョブで、ジョブのエラー時にSnowflakeの一時STAGEが削除されていること。

2024-02-26 08:04 UTC, d-hrs requested changes
for backward compatibility, please make it the option like `delete_stage` and defualt `false` (do not delete stage).

I think the presence of a stage is helpful for investigate the errors.

2024-02-29 07:50 UTC, kekekenta commented
@maeken Would you share an example config for reproduce the error?

2024-02-29 09:42 UTC, maeken commented
@kekekenta 
Here is a sample config yaml to get an error, content of sample csv, and result log.
```
in:
  type: file
  path_prefix: ./test.csv
  parser:
    type: csv
    delimiter: ","
    skip_header_lines: 0
    null_string: ""
    columns:
      - { name: col1, type: long }
      - { name: col2, type: string }
    stop_on_invalid_record: true

out:
  type: snowflake
  host: <YOUR_SNOWFLAKE_HOST>
  user: <YOUR_SNOWFLAKE_USER>
  password: <YOUR_SNOWFLAKE_PASSWORD>
  warehouse: <YOUR_SNOWFLAKE_WAREHOUSE>
  database: <YOUR_SNOWFLAKE_DATABASE>
  schema: <YOUR_SNOWFLAKE_SCHEMA>
  table: <YOUR_SNOWFLAKE_TABLE>
  delete_stage: true
  delete_stage_on_error: true
  retry_limit: 1
  retry_wait: 1000
  max_retry_wait: 1800000
  mode: replace
  default_timezone: UTC
```

and content of test.csv
```
"hogehogefugafuga","90123456789"
"hogehgoe21928398","B01234567890123456789"
"hogeho8dyf9e","C01234567890123456789012345678901234567890123456789"
```

and result log
```
2024-02-29 09:36:07.947 +0000: Embulk v0.9.26
2024-02-29 09:36:08.567 +0000 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2024-02-29 09:36:09.941 +0000 [INFO] (main): BUNDLE_GEMFILE is being set: "/work/embulk_bundle/Gemfile"
2024-02-29 09:36:09.941 +0000 [INFO] (main): Gem's home and path are being cleared.
You must use Bundler 2 or greater with this lockfile.
2024-02-29 09:36:11.071 +0000 [INFO] (main): Started Embulk v0.9.26
2024-02-29 09:36:11.135 +0000 [INFO] (0001:transaction): Loaded plugin embulk/output/snowflake from a load path
2024-02-29 09:36:11.167 +0000 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'test.csv'
2024-02-29 09:36:11.168 +0000 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2024-02-29 09:36:11.171 +0000 [INFO] (0001:transaction): Loading files [./test.csv]
2024-02-29 09:36:11.191 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=16 / output tasks 8 = input tasks 1 * 8
2024-02-29 09:36:11.208 +0000 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:11.219 +0000 [INFO] (0001:transaction): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:12.064 +0000 [INFO] (0001:transaction): TransactionIsolation=unknown
2024-02-29 09:36:12.325 +0000 [INFO] (0001:transaction): SQL: CREATE STAGE IF NOT EXISTS TEST_BY_MAEKEN.TEST_SCHEMA.embulk_snowflake_20240229ARpVxc;
2024-02-29 09:36:12.327 +0000 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:12.329 +0000 [INFO] (0001:transaction): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:12.756 +0000 [INFO] (0001:transaction): TransactionIsolation=unknown
2024-02-29 09:36:12.756 +0000 [INFO] (0001:transaction): Using JDBC Driver 3.13.26
2024-02-29 09:36:12.756 +0000 [INFO] (0001:transaction): Using replace mode
2024-02-29 09:36:12.901 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE "STAGE_DELETE_TEST_0000018df438b265_embulk" ("col1" BIGINT, "col2" VARCHAR(65535))
2024-02-29 09:36:13.231 +0000 [INFO] (0001:transaction): > 0.33 seconds
2024-02-29 09:36:13.674 +0000 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2024-02-29 09:36:13.679 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:13.680 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:13.689 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:13.846 +0000 [INFO] (0016:task-0000): TransactionIsolation=unknown
2024-02-29 09:36:13.849 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:13.849 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:13.850 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:13.987 +0000 [INFO] (0016:task-0000): TransactionIsolation=unknown
2024-02-29 09:36:13.987 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:13.988 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:13.989 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:14.170 +0000 [INFO] (0016:task-0000): TransactionIsolation=unknown
2024-02-29 09:36:14.171 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:14.171 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:14.173 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:14.322 +0000 [INFO] (0016:task-0000): TransactionIsolation=unknown
2024-02-29 09:36:14.323 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:14.323 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:14.324 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:14.522 +0000 [INFO] (0016:task-0000): TransactionIsolation=unknown
2024-02-29 09:36:14.523 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:14.523 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:14.525 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true}
2024-02-29 09:36:14.654 +0000 [INFO] (0016:task-0000): TransactionIsolation=unknown
2024-02-29 09:36:14.655 +0000 [WARN] (0016:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2024-02-29 09:36:14.655 +0000 [WARN] (0016:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2024-02-29 09:36:14.656 +0000 [INFO] (0016:task-0000): Connecting to jdbc:snowflake://nz47967.ap-northeast-1.aws.snowflakecomputing.com options {user=pn, warehouse=COMPUTE_WH, db=TEST_BY_MAEKEN, password=***, schema=TEST_SCHEMA, MULTI_STATEMENT_COUNT=0, CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=t [...]

2024-02-29 10:16 UTC, kekekenta commented on src/main/java/org/embulk/output/SnowflakeOutputPlugin.java
> +    this.stageIdentifier = StageIdentifierHolder.getStageIdentifier(t);
It seems that we don't have to define `stageIdentifier` as property. (as `this.stageIdentifier`)
`stageIdentifier` can be local variable.

2024-02-29 10:17 UTC, kekekenta commented on src/main/java/org/embulk/output/SnowflakeOutputPlugin.java
> +    this.stageIdentifier = StageIdentifierHolder.getStageIdentifier(pluginTask);
`this.stageIdentifier` can be local variable?

2024-02-29 10:17 UTC, kekekenta requested changes
commented

2024-03-01 03:51 UTC, kekekenta approved these changes
LGTM

2024-03-11 05:54 UTC, d-hrs approved these changes
LGTM

2024-03-11 08:22 UTC, merged